catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9

overrides:
  vite: "catalog:"

patchedDependencies:
  shadcn@4.19.1: patches/shadcn@4.19.1.patch

peerDependencyRules:
  allowAny: [vite]
  allowedVersions:
    vite: "*"

update:
  ignoreDeps: [vite, vite-plus]
