// Workspace-wide Vite+ toolchain config: formatting, linting, staged
// pre-commit checks, and task caching. Linter rules for all packages
// live here because Vite+ does not support per-package linter config.

import { defineConfig, mergeConfig, type UserConfig } from "vite-plus";

/**
 * Default Oxlint config. This is needed as a baseline because if any
 * other configs define a custom plugins array, the merged array will
 * replace the default set unless it is included in the merged array.
 *
 * Taken from:
 * https://oxc.rs/docs/guide/usage/linter/plugins.html#supported-plugins
 */
const baseConfig: UserConfig = {
  lint: { plugins: ["eslint", "typescript", "unicorn", "oxc"] },
};

/**
 * Standard Vite+ config generated by `vp create vite:application`.
 */
const vitePlusConfig: UserConfig = {
  staged: { "*": "vp check --fix" },
  fmt: {},
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
};

/**
 * Project-specific config which keeps the formatter out of `docs/`
 * (prose, not code).
 */
const projectConfig: UserConfig = {
  fmt: { ignorePatterns: ["docs/"] },
};

/**
 * Merges the given configs left-to-right with `mergeConfig`, so later
 * configs take precedence, and the result is passed to `defineConfig`.
 */
function defineMergedConfig(configs: UserConfig[]) {
  return defineConfig(configs.reduce((merged, next) => mergeConfig(merged, next), {}));
}

export default defineMergedConfig([baseConfig, vitePlusConfig, projectConfig]);
